[tool.poetry]
package-mode=false

[tool.poetry.dependencies]
python="^3.13"
fastapi = {extras = ["all"], version = "^0.115.6"}
pydantic = "^2.10.5"
pydantic-settings = "^2.7.1"
alembic = "^1.14.1"
black = "^24.10.0"
asyncpg = "^0.30.0"
psycopg2 = "^2.9.10"
